import { motion } from "framer-motion";
import { useScrollReveal } from "../hooks/useScrollReveal";

type ContentItem = {
    text: string;
    bold?: boolean;
};

type TermsSection = {
    title: string;
    content: ContentItem[];
};

const termsSections: TermsSection[] = [
    {
        title: "About Our Services",
        content: [
            {
                text: "Read Sidekick is a Chrome extension designed to assist users with reading comprehension by transforming text into more accessible formats. Our Services include text simplification across multiple reading levels (Easy, Medium, Hard), and may include American Sign Language (ASL) translation features. These tools are intended to support literacy development and accessibility.",
            },
        ],
    },
    {
        title: "Eligibility and Registration",
        content: [
            {
                text: "Minimum Age. You must be at least 13 years old or the minimum age required in your country to consent to use the Services. If you are under 18, you must have your parent or legal guardian's permission to use the Services.",
            },
            {
                text: "Account Information. If you create an account, you must provide accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
            },
        ],
    },
    {
        title: "Using Our Services",
        content: [
            {
                text: "Permitted Use. Subject to your compliance with these Terms, you may access and use our Services for personal, non-commercial purposes. You must comply with all applicable laws when using our Services.",
            },
            {
                text: "Prohibited Conduct. You may not: (a) use our Services for any illegal, harmful, or abusive activity; (b) attempt to reverse engineer, decompile, or discover the source code or underlying components of our Services; (c) interfere with or disrupt our Services; (d) use automated means to access or extract data from our Services; (e) misrepresent the source of any output as original human-generated content; or (f) use the Services in any manner that infringes the rights of others.",
            },
        ],
    },
    {
        title: "Content and Data",
        content: [
            {
                text: 'Your Input. You may provide text content to the Services for processing ("Input"). You retain ownership of your Input and are responsible for ensuring you have the right to submit such content to our Services.',
            },
            {
                text: 'Output. Our Services will generate simplified text, translations, or other processed content based on your Input ("Output"). You acknowledge that Output is generated automatically and may be used by you subject to the disclaimers and limitations set forth in these Terms.',
            },
            {
                text: "Data Collection. We may collect and process data related to your use of the Services, including text you submit for processing. Please review our Privacy Policy for details on how we collect, use, and protect your information.",
            },
        ],
    },
    {
        title: "Important Disclaimers Regarding Accuracy",
        content: [
            {
                text: 'USE AT YOUR OWN RISK. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. THE SERVICES, INCLUDING ALL TEXT SIMPLIFICATION, READING LEVEL ADJUSTMENTS, ASL TRANSLATIONS, AND OTHER OUTPUTS, ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS.',
                bold: true,
            },
            {
                text: "NO GUARANTEE OF ACCURACY. READ SIDEKICK DOES NOT GUARANTEE THE ACCURACY, COMPLETENESS, RELIABILITY, OR CORRECTNESS OF ANY OUTPUT GENERATED BY THE SERVICES. Text simplification, reading level adjustments, and ASL translations are generated using automated processes and artificial intelligence, which may produce errors, omissions, or inaccuracies.",
                bold: true,
            },
            {
                text: "YOU MUST VERIFY ALL OUTPUT. You are solely responsible for reviewing, verifying, and validating all Output before relying upon it or sharing it with others. You should not rely on Output as a sole source of truth or factual information. Always cross-reference Output with original sources and use your own judgment.",
                bold: true,
            },
            {
                text: "ASL TRANSLATION LIMITATIONS. If you use our ASL translation features, you acknowledge that ASL is a distinct language with its own grammar and syntax. Automated translations may not accurately capture nuances, may use incorrect signs, or may produce grammatically incorrect ASL gloss. ASL translations are provided as a supplementary aid only and should not be relied upon for critical communications or professional interpretation services.",
                bold: true,
            },
            {
                text: "NOT A SUBSTITUTE FOR PROFESSIONAL SERVICES. The Services are not a substitute for professional educational instruction, medical advice, legal advice, or certified interpretation services. Do not use Output for any purpose where accuracy is critical, including but not limited to: educational assessments, legal documents, medical instructions, safety communications, or professional certifications.",
                bold: true,
            },
        ],
    },
    {
        title: "Disclaimer of Warranties",
        content: [
            {
                text: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, READ SIDEKICK AND ITS AFFILIATES, LICENSORS, AND SERVICE PROVIDERS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.",
                bold: true,
            },
            {
                text: "WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT WARRANT THAT ANY OUTPUT WILL BE ACCURATE, COMPLETE, RELIABLE, CURRENT, OR ERROR-FREE.",
                bold: true,
            },
        ],
    },
    {
        title: "Limitation of Liability",
        content: [
            {
                text: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL READ SIDEKICK, ITS AFFILIATES, LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICES, ANY OUTPUT GENERATED BY THE SERVICES, OR ANY ERRORS OR INACCURACIES IN SUCH OUTPUT.",
                bold: true,
            },
            {
                text: "IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICES EXCEED THE GREATER OF (A) THE AMOUNT YOU HAVE PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100).",
                bold: true,
            },
            {
                text: "Some jurisdictions do not allow the exclusion or limitation of certain warranties or liability, so some of the above limitations may not apply to you. In such cases, our liability will be limited to the maximum extent permitted by law.",
            },
        ],
    },
    {
        title: "Indemnification",
        content: [
            {
                text: "You agree to indemnify, defend, and hold harmless Read Sidekick and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) your use of the Services; (b) your violation of these Terms; (c) your violation of any rights of another party; or (d) your reliance on any Output generated by the Services.",
            },
        ],
    },
    {
        title: "Intellectual Property",
        content: [
            {
                text: "The Services, including all software, algorithms, designs, text, graphics, and other content (excluding your Input), are owned by Read Sidekick or its licensors and are protected by intellectual property laws. You may not copy, modify, distribute, sell, or lease any part of our Services without our prior written consent.",
            },
        ],
    },
    {
        title: "Termination",
        content: [
            {
                text: "You may stop using the Services and uninstall the Chrome extension at any time. We reserve the right to suspend or terminate your access to the Services at any time, with or without cause and with or without notice, including if we believe you have violated these Terms.",
            },
        ],
    },
    {
        title: "Changes to These Terms",
        content: [
            {
                text: 'We may update these Terms from time to time. If we make material changes, we will notify you by posting the updated Terms on our website and updating the "Effective Date" above. Your continued use of the Services after any changes constitutes your acceptance of the new Terms.',
            },
        ],
    },
    {
        title: "Governing Law and Dispute Resolution",
        content: [
            {
                text: "These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions. Any dispute arising out of or relating to these Terms or the Services shall be resolved exclusively in the state or federal courts located in San Francisco County, California, and you consent to the personal jurisdiction of such courts.",
            },
        ],
    },
    {
        title: "Severability",
        content: [
            {
                text: "If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.",
            },
        ],
    },
    {
        title: "Entire Agreement",
        content: [
            {
                text: "These Terms, together with our Privacy Policy, constitute the entire agreement between you and Read Sidekick regarding the Services and supersede all prior agreements and understandings.",
            },
        ],
    },
    {
        title: "Contact Us",
        content: [
            {
                text: "If you have any questions about these Terms, please contact us at: Read Sidekick | Website: readsidekick.com | Email: hello@readsidekick.com",
            },
        ],
    },
];

export function TermsOfService() {
    const { ref: sectionRef, isInView: sectionInView } =
        useScrollReveal<HTMLElement>({
            threshold: 0.1,
        });

    return (
        <section
            ref={sectionRef}
            className="relative py-editorial bg-ivory-100 overflow-hidden min-h-screen"
        >
            <div className="editorial-container">
                <div className="max-w-3xl mx-auto">
                    {/* Header */}
                    <div className="text-center mb-12 md:mb-16">
                        <motion.span
                            initial={{ opacity: 0, y: 20 }}
                            animate={{
                                opacity: sectionInView ? 1 : 0,
                                y: sectionInView ? 0 : 20,
                            }}
                            transition={{
                                duration: 0.8,
                                ease: [0.16, 1, 0.3, 1],
                            }}
                            className="editorial-label block mb-6"
                        >
                            Effective Date: January 20, 2026
                        </motion.span>

                        <motion.h1
                            initial={{ opacity: 0, y: 40 }}
                            animate={{
                                opacity: sectionInView ? 1 : 0,
                                y: sectionInView ? 0 : 40,
                            }}
                            transition={{
                                duration: 1,
                                delay: 0.1,
                                ease: [0.16, 1, 0.3, 1],
                            }}
                            className="font-serif text-display-md md:text-display-lg text-ink-900 mb-4"
                        >
                            Terms of Service
                        </motion.h1>

                        <motion.p
                            initial={{ opacity: 0, y: 30 }}
                            animate={{
                                opacity: sectionInView ? 1 : 0,
                                y: sectionInView ? 0 : 30,
                            }}
                            transition={{
                                duration: 0.8,
                                delay: 0.15,
                                ease: [0.16, 1, 0.3, 1],
                            }}
                            className="font-mono text-body-sm text-ink-700/60"
                        >
                            Read Sidekick Chrome Extension
                        </motion.p>
                    </div>

                    {/* Intro */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{
                            opacity: sectionInView ? 1 : 0,
                            y: sectionInView ? 0 : 30,
                        }}
                        transition={{
                            duration: 0.8,
                            delay: 0.2,
                            ease: [0.16, 1, 0.3, 1],
                        }}
                        className="mb-10 md:mb-12 space-y-4"
                    >
                        <p className="font-mono text-body-md text-ink-700/80 leading-relaxed">
                            Thank you for using Read Sidekick!
                        </p>
                        <p className="font-mono text-body-md text-ink-700/80 leading-relaxed">
                            These Terms of Service ("Terms") apply to your use
                            of the Read Sidekick Chrome extension, website at
                            readsidekick.com, and any associated services
                            (collectively, the "Services"). By installing,
                            accessing, or using our Services, you agree to be
                            bound by these Terms. If you do not agree to these
                            Terms, please do not use our Services.
                        </p>
                    </motion.div>

                    {/* Terms Sections */}
                    <div className="space-y-10 md:space-y-12">
                        {termsSections.map((section, index) => (
                            <motion.div
                                key={index}
                                initial={{ opacity: 0, y: 30 }}
                                animate={{
                                    opacity: sectionInView ? 1 : 0,
                                    y: sectionInView ? 0 : 30,
                                }}
                                transition={{
                                    duration: 0.8,
                                    delay: 0.3 + index * 0.05,
                                    ease: [0.16, 1, 0.3, 1],
                                }}
                                className="space-y-4"
                            >
                                <h2 className="font-serif text-display-sm text-ink-900">
                                    {section.title}
                                </h2>
                                {section.content.map((item, itemIndex) => (
                                    <p
                                        key={itemIndex}
                                        className={`font-mono text-body-md leading-relaxed ${
                                            item.bold
                                                ? "text-ink-900 font-semibold"
                                                : "text-ink-700/80"
                                        }`}
                                    >
                                        {item.text}
                                    </p>
                                ))}
                            </motion.div>
                        ))}
                    </div>

                    {/* Final Notice */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{
                            opacity: sectionInView ? 1 : 0,
                            y: sectionInView ? 0 : 30,
                        }}
                        transition={{
                            duration: 0.8,
                            delay: 0.3 + termsSections.length * 0.05,
                            ease: [0.16, 1, 0.3, 1],
                        }}
                        className="mt-12 md:mt-16 pt-8 border-t border-ink-800/10"
                    >
                        <p className="font-mono text-body-md text-ink-900 font-semibold leading-relaxed">
                            BY USING READ SIDEKICK, YOU ACKNOWLEDGE THAT YOU
                            HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY
                            THESE TERMS OF SERVICE, INCLUDING THE DISCLAIMERS
                            REGARDING ACCURACY AND THE LIMITATION OF LIABILITY.
                        </p>
                    </motion.div>
                </div>
            </div>

            <div className="absolute bottom-0 left-0 right-0 h-px bg-ink-800/10" />
        </section>
    );
}
